DROP TABLE IF EXISTS Key_Table;

CREATE TABLE Key_Table(
	KEY_ID				INT AUTO_INCREMENT,
	KEY_REF_EMP_ID_Number		INT,
	KEY_Keys			TEXT,
	PRIMARY KEY ( KEY_ID ),
	INDEX ( KEY_REF_EMP_ID_Number ),
	FOREIGN KEY (KEY_REF_EMP_ID_Number) REFERENCES Employee_Table( EMP_ID_Number )
)type=InnoDB
