DROP TABLE IF EXISTS Login_Table;

CREATE TABLE Login_Table(
	LOG_ID		INT NOT NULL AUTO_INCREMENT,
	LOG_REF_EMP_ID	INT NOT NULL,
	LOG_Time_In	DATETIME,
	LOG_Time_Out	DATETIME,
	LOG_Count	INT,
	Primary Key(LOG_ID),
	UNIQUE(LOG_REF_EMP_ID, LOG_Time_In, LOG_Time_Out, LOG_Count),
	INDEX(LOG_REF_EMP_ID),
	FOREIGN KEY (LOG_REF_EMP_ID) REFERENCES Employee_Table(EMP_ID_Number)
);
